from .exceptions import CellCoordinatesException as CellCoordinatesException
from _typeshed import Incomplete
from collections.abc import Generator
from itertools import chain as chain, product as product

COORD_RE: Incomplete
COL_RANGE: str
ROW_RANGE: str
RANGE_EXPR: str
ABSOLUTE_RE: Incomplete
SHEET_TITLE: str
SHEETRANGE_RE: Incomplete

def get_column_interval(start, end): ...
def coordinate_from_string(coord_string): ...
def absolute_coordinate(coord_string): ...
def get_column_letter(col_idx): ...
def column_index_from_string(col): ...
def range_boundaries(range_string): ...
def rows_from_range(range_string) -> Generator[Incomplete]: ...
def cols_from_range(range_string) -> Generator[Incomplete]: ...
def coordinate_to_tuple(coordinate): ...
def range_to_tuple(range_string): ...
def quote_sheetname(sheetname): ...
