from _typeshed import Incomplete

class IndexedList(list):
    clean: bool
    def __init__(self, iterable: Incomplete | None = None) -> None: ...
    def __contains__(self, value) -> bool: ...
    def index(self, value): ...
    def append(self, value) -> None: ...
    def add(self, value): ...
