from _typeshed import Incomplete
from openpyxl.cell.text import InlineFont as InlineFont, Text as Text
from openpyxl.compat import NUMERIC_TYPES as NUMERIC_TYPES
from openpyxl.descriptors import Strict as Strict, String as String, Typed as Typed
from openpyxl.xml.functions import Element as Element, whitespace as whitespace

class TextBlock(Strict):
    font: Incomplete
    text: Incomplete
    def __init__(self, font, text) -> None: ...
    def __eq__(self, other): ...
    def to_tree(self): ...

class CellRichText(list):
    def __init__(self, *args) -> None: ...
    @classmethod
    def from_tree(cls, node): ...
    def __iadd__(self, arg): ...
    def __add__(self, arg): ...
    def __setitem__(self, indx, val) -> None: ...
    def append(self, arg) -> None: ...
    def extend(self, arg) -> None: ...
    def as_list(self): ...
    def to_tree(self): ...
