from openpyxl.xml.functions import Element as Element

class ElementList(list):
    @property
    def tagname(self) -> None: ...
    @property
    def expected_type(self) -> None: ...
    @classmethod
    def from_tree(cls, tree): ...
    def to_tree(self): ...
    def append(self, value) -> None: ...
