name: Reusable Build Workflow

on:
  workflow_call:
    inputs:
      ENV_FILE_PATH:
        required: false
        type: string
        default: ".env"
      repo_name:
        required: false
        type: string
    secrets:
      QUALER_EMAIL:
        required: false
      QUALER_PASSWORD:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Load environment variables
        run: |
          if [ -f "${{ inputs.ENV_FILE_PATH }}" ]; then
            echo "Loading environment variables from ${{ inputs.ENV_FILE_PATH }}"
            cat "${{ inputs.ENV_FILE_PATH }}" >> $GITHUB_ENV
          else
            echo "Warning: .env file not found"
          fi

      - name: Display environment variables (for debugging)
        run: env | sort

      - name: Validate required environment variables
        run: |
          REQUIRED_VARS=("SOP_ID" "DOC_ID" "DOC_TITLE" "DOC_DETAILS")
          MISSING_VARS=()
          
          for VAR in "${REQUIRED_VARS[@]}"; do
            if [[ -z "${!VAR}" ]]; then
              MISSING_VARS+=("$VAR")
            fi
          done

          if [[ ${#MISSING_VARS[@]} -ne 0 ]]; then
            echo "Error: Missing required environment variables: ${MISSING_VARS[*]}"
            exit 1
          fi

      - name: Validate Secrets
        run: |
          if [[ -z "${{ secrets.QUALER_EMAIL }}" || -z "${{ secrets.QUALER_PASSWORD }}" ]]; then
            echo "❌ Missing required secrets."
            exit 1
          fi
