name: Reusable Build Workflow

on:
  workflow_call:
    inputs:
      ENV_FILE_PATH:
        required: false
        type: string
        default: ".env"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Load environment variables
        run: |
          if [ -f "${{ inputs.ENV_FILE_PATH }}" ]; then
            echo "Loading environment variables from ${{ inputs.ENV_FILE_PATH }}"
            cat "${{ inputs.ENV_FILE_PATH }}" >> $GITHUB_ENV
          else
            echo "Warning: .env file not found"
          fi

      - name: Display environment variables (for debugging)
        run: env | sort

      - name: Validate environment variables (SOP_ID, DOC_ID, DOC_TITLE, DOC_DETAILS)
        run: |
          if [[ -z "${{ env.SOP_ID }}" || -z "${{ env.DOC_ID }}" || -z "${{ env.DOC_TITLE }}" || -z "${{ env.DOC_DETAILS }}" ]]; then
            echo "❌ Missing required environment variables."
            exit 1
          fi
