# ./ci-scripts.build.yml
name: Reusable Build Workflow

on:
  workflow_call:
    inputs:
      ENV_FILE_PATH:
        required: false
        type: string
        default: ".env"
      repo_name:
        required: false
        type: string
    secrets:
      QUALER_EMAIL:
        required: false
      QUALER_PASSWORD:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Load environment variables
        run: |
          if [ -f "${{ inputs.ENV_FILE_PATH }}" ]; then
            echo "Loading environment variables from ${{ inputs.ENV_FILE_PATH }}"
            cat "${{ inputs.ENV_FILE_PATH }}" >> $GITHUB_ENV
          else
            echo "Warning: .env file not found"
          fi

      - name: Display environment variables (for debugging)
        run: env | sort

      - name: Validate required environment variables
        run: |
          REQUIRED_VARS=("SOP_ID" "DOC_ID" "DOC_TITLE" "DOC_DETAILS")
          MISSING_VARS=()
          
          for VAR in "${REQUIRED_VARS[@]}"; do
            if [[ -z "${!VAR}" ]]; then
              MISSING_VARS+=("$VAR")
            fi
          done

          if [[ ${#MISSING_VARS[@]} -ne 0 ]]; then
            echo "Error: Missing required environment variables: ${MISSING_VARS[*]}"
            exit 1
          fi

      - name: Validate Secrets
        run: |
          if [[ -z "${{ secrets.QUALER_EMAIL }}" || -z "${{ secrets.QUALER_PASSWORD }}" ]]; then
            echo "❌ Missing required secrets."
            exit 1
          fi

      - name: Debug - show files in the current directory
        run: ls -al

      - name: Debug - show all excel files ("*.xl...")
        run: find -type f -name "*.xl*"

      - name: Count Excel files
        run: |
            EXCEL_COUNT=$(find . -type f -iname "*.xls*" | wc -l)
            echo "Excel files found: $EXCEL_COUNT"
            echo "EXCEL_COUNT=$EXCEL_COUNT" >> $GITHUB_ENV
            
      - name: Handle Excel file count
        run: |
            if [ "$EXCEL_COUNT" -eq 0 ]; then
              echo "✅ No Excel files found. Exiting without error."
              exit 0
            elif [ "$EXCEL_COUNT" -eq 1 ]; then
              EXCEL_FILE=$(find . -type f -iname "*.xls*" | head -n 1)
              echo "✅ Using Excel file: $EXCEL_FILE"
              echo "EXCEL_FILE=$EXCEL_FILE" >> $GITHUB_ENV
            else
              echo "❌ More than one Excel file found! Exiting with error."
              exit 1
            fi

      - name: Check for Excel file changes
        run: |
            git diff --quiet HEAD^ HEAD -- $EXCEL_FILE
            if [ $? -eq 0 ]; then
              echo "✅ No changes to Excel file. Exiting without error."
              exit 0
            fi
