name: Apply Branch Protection to xl-* Repos

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  apply-branch-protection:
    runs-on: ubuntu-latest

    steps:
      - name: Ensure correct working directory
        run: cd $GITHUB_WORKSPACE

      - name: Set up GitHub CLI
        run: |
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

      - name: Get list of xl-* repositories
        id: list-repos
        run: |
          gh repo list Johnson-Gage-Inspection-Inc --json name --jq '.[] | select(.name | startswith("xl-")) | .name' > repos.txt

      - name: Apply branch protection to each xl-* repo
        run: |
          while read -r REPO; do
            echo "Applying branch protection to $REPO..."
            gh api --method PUT \
              -H "Accept: application/vnd.github+json" \
              -H "Content-Type: application/json" \
              "/repos/Johnson-Gage-Inspection-Inc/$REPO/branches/main/protection" \
              --input "$GITHUB_WORKSPACE/main-protection.json"
          done < repos.txt
